apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  lifecycle: experimental
  type: service
  owner: ${{ values.owner | dump }}
